[project]
name = "video2slider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdown>=5.2.0",
    "groq>=0.33.0",
    "litellm>=1.79.3",
    "moviepy>=2.2.1",
    "pillow>=11.3.0",
    "python-dotenv>=1.2.1",
]
